local HeadlessInput = require("core/lua/headless_input")

describe("HeadlessInput", function()
    it("new() starts with nothing down or pressed", function()
        local inp = HeadlessInput.new()
        assert.is_false(inp:is_down("fwd"))
        assert.is_false(inp:pressed("fwd"))
    end)

    it("press() sets is_down and pressed on the same frame", function()
        local inp = HeadlessInput.new()
        inp:press("fwd")
        assert.is_true(inp:is_down("fwd"))
        assert.is_true(inp:pressed("fwd"))
    end)

    it("update() clears pressed but leaves is_down after press()", function()
        local inp = HeadlessInput.new()
        inp:press("fwd")
        inp:update()
        assert.is_false(inp:pressed("fwd"))
        assert.is_false(inp:is_down("fwd"))
    end)

    it("hold() sets is_down and pressed on the first call", function()
        local inp = HeadlessInput.new()
        inp:hold("fwd")
        assert.is_true(inp:is_down("fwd"))
        assert.is_true(inp:pressed("fwd"))
    end)

    it("hold() after update() keeps is_down but not pressed", function()
        local inp = HeadlessInput.new()
        inp:hold("fwd")
        inp:update()
        assert.is_true(inp:is_down("fwd"))
        assert.is_false(inp:pressed("fwd"))
    end)

    it("hold() called again after update() does not re-trigger pressed", function()
        local inp = HeadlessInput.new()
        inp:hold("fwd")
        inp:update()
        inp:hold("fwd")
        assert.is_false(inp:pressed("fwd"))
        assert.is_true(inp:is_down("fwd"))
    end)

    it("release() clears both is_down and pressed", function()
        local inp = HeadlessInput.new()
        inp:hold("fwd")
        inp:release("fwd")
        assert.is_false(inp:is_down("fwd"))
        assert.is_false(inp:pressed("fwd"))
    end)

    it("update() only clears pressed, not unrelated held actions", function()
        local inp = HeadlessInput.new()
        inp:hold("fwd")
        inp:press("use")
        inp:update()
        assert.is_true(inp:is_down("fwd"))
        assert.is_false(inp:pressed("use"))
    end)

    it("multiple independent actions do not interfere", function()
        local inp = HeadlessInput.new()
        inp:press("left")
        inp:hold("right")
        assert.is_true(inp:pressed("left"))
        assert.is_true(inp:pressed("right"))
        inp:update()
        assert.is_false(inp:pressed("left"))
        assert.is_true(inp:is_down("right"))
    end)
end)
